---
title: "Poranna prasówka GPW – 9 kwietnia 2026"
date: "2026-04-09"
categories: [Giełda, Prasówka, GPW]
description: "Najważniejsze informacje przed sesją: WIG20 na historycznym maksimum, KGHM z fenomenalnym wzrostem, wyniki spółek za I kwartał 2026."
seo:
  title: "Prasówka GPW 09.04.2026 – Rekord WIG20 i wzrost KGHM"
  description: "Zbiór najważniejszych wiadomości giełdowych z 9 kwietnia 2026 r. Sprawdź, co wpłynie na dzisiejszą sesję na GPW."
---

# Poranna prasówka GPW – 09.04.2026

Środowa sesja przyniosła historyczne wydarzenie na warszawskim parkiecie. Indeks WIG20 osiągnął najwyższy poziom od 2008 roku, a indeks szerokiego rynku WIG zamknął się na rekordzie. Kierunek nadawała informacja o rozejmie USA-Iran i otwarciu cieśniny Ormuz.

### Wyniki sesji (8 kwietnia)

*   **WIG20 wzrósł o 3,4%** – najwyższy poziom od 2008 roku
*   **WIG na historycznym maksimum**
*   **mWIG40 +2,9%, sWIG80 +1,4%**

*Źródła: [Business Insider](https://businessinsider.com.pl/gielda/wiadomosci/gielda-reaguje-na-zawieszenie-broni-tylko-orlen-i-tauron-na-minusie/xxe7gbx){rel="nofollow"}, [WNP.pl](https://www.wnp.pl/rynki/na-gpw-dzien-euforii-naznaczony-rekordami-pytanie-co-dalej,1050339.html){rel="nofollow"}, [Strefa Biznesu](https://strefabiznesu.pl/pozytywny-sentyment-na-gpw-mimo-spadkow-jednego-z-liderow/ar/c1p2-28890699){rel="nofollow"}*

### Kluczowe informacje ze spółek

*   **KGHM z fenomenalnym wzrostem**
    Akcje KGHM wystrzeliły o **+9,9%** na fali wzrostu cen metali przemysłowych (miedź, srebro, pallad, platyna) oraz euforycznych nastrojów po rozejmie.
    *Źródła: [WNP.pl](https://www.wnp.pl/rynki/na-gpw-dzien-euforii-naznaczony-rekordami-pytanie-co-dalej,1050339.html){rel="nofollow"}, [BiznesPAP](https://biznes.pap.pl/wiadomosci/firmy/dzien-na-gpw-wig20-i-wig-na-nowych-rekordach-mocne-kghm-i-spolki-budowlane-ale){rel="nofollow"}*

*   **Orlen pod presją regulacyjną**
    Kurs Orlenu spadł o **6,4%** do 126,4 zł. Presję wywierają obawy o nowy podatek od nadmiarowych zysków koncernów paliwowych, który Minister Finansów planuje przedstawić w kwietniu.
    *Źródła: [Strefa Biznesu](https://strefabiznesu.pl/pozytywny-sentyment-na-gpw-mimo-spadkow-jednego-z-liderow/ar/c1p2-28890699){rel="nofollow"}, [Bankier.pl](https://www.bankier.pl/wiadomosc/Projekt-ustawy-o-nadmiarowych-zyskach-koncernow-paliwowych-w-kwietniu-Domanski-MF-9110421.html){rel="nofollow"}*

*   **Medicalgorithmics: szacunki za I kwartał 2026**
    Skonsolidowane przychody: **10,2 mln zł** (vs 6,8 mln zł rok wcześniej). EBITDA szacowana na **1 mln zł**.
    *Źródła: [Bankier.pl](https://www.bankier.pl/wiadomosc/Medicalgorithmics-szacuje-przychody-w-I-kw-na-10-2-mln-zl-EBITDA-na-1-mln-zl-9111135.html){rel="nofollow"}, [StockWatch](https://www.stockwatch.pl/wiadomosci){rel="nofollow"}*

*   **Ipopema podnosi cenę docelową dla Asbisu**
    Analitycy Ipopema Securities podwyższyli cenę docelową do **60,4 zł** z 36,73 zł, utrzymując rekomendację „kupuj".
    *Źródła: [Bankier.pl](https://www.bankier.pl/wiadomosc/Ipopema-podnosi-cene-docelowa-dla-Asbisu-do-60-4-zl-9111139.html){rel="nofollow"}*

*   **Answear: przychody I kwartał 2026**
    Skonsolidowana sprzedaż: **375,7 mln zł**, +6,6% r/r.
    *Źródła: [StockWatch](https://www.stockwatch.pl/wiadomosci/answear-zwiekszyl-przychody-o-66-proc-r-r-do-3757-mln-zl-w-i-kw-2026-r,akcje,369700){rel="nofollow"}, [Parkiet](https://www.parkiet.com/komunikaty-espi/art44115121-answear-com-spolka-akcyjna-wstepne-wybrane-dane-dotyczace-sprzedazy-answear-com-sa-za-i-kwartal-2026-r){rel="nofollow"}*

*   **Auto Partner: przychody w marcu 2026**
    Wzrost o **19,5%** r/r.
    *Źródła: [StockWatch](https://www.stockwatch.pl/wiadomosci/auto-partner-przychody-marzec-i-kwartal-2026,akcje,369751){rel="nofollow"}, [Parkiet](https://www.parkiet.com/komunikaty-espi/art44117541-auto-partner-spolka-akcyjna-informacja-poufna-raport-miesieczny-o-przychodach-ze-sprzedazy-za-marzec-2026-roku){rel="nofollow"}*

*   **Wielki strajk Lufthansy**
    Personel pokładowy zapowiedział strajk na piątek. Zakłócenia mogą dotyczyć także lotów do i z Polski.
    *Źródła: [Bankier.pl](https://www.bankier.pl/wiadomosc/Wielki-strajk-Lufthansy-uderzy-w-glowne-lotniska-Ucierpia-tez-pasazerowie-w-Polsce-9111108.html){rel="nofollow"}*

### Otoczenie rynkowe

*   **Ropa WTI:** Po gwałtownym spadku o ok. 14% (do 96 USD) w reakcji na rozejm, ceny znów rosną
*   **Waluty:** USD/PLN w okolicach 3,64

---
*Prasówka przygotowana na podstawie publicznych komunikatów i serwisów informacyjnych. Dane aktualne na godzinę 08:30.*