---
title: "Poranna prasówka GPW – 8 kwietnia 2026"
date: "2026-04-08"
categories: [Giełda, Prasówka, GPW]
description: "Najważniejsze informacje przed sesją: deeskalacja na Bliskim Wschodzie, IPO Rex Concepts (Burger King/Popeyes) oraz przetasowania w spółkach Skarbu Państwa."
seo:
  title: "Prasówka GPW 08.04.2026 – IPO Rex Concepts i Rozejm USA-Iran"
  description: "Zbiór najważniejszych wiadomości giełdowych z 8 kwietnia 2026 r. Sprawdź, co wpłynie na dzisiejszą sesję na GPW."
---

# Poranna prasówka GPW – 08.04.2026

Dzień przynosi wyraźną deeskalację napięć na arenie międzynarodowej, co przekłada się na entuzjazm na rynkach azjatyckich i znaczące spadki cen surowców energetycznych. Na rodzimym podwórku uwaga skupia się na zapowiedzi dużego debiutu oraz zmianach kadrowych w kluczowych spółkach.

### Kluczowe informacje ze spółek

*   **Rex Concepts (Burger King i Popeyes) zmierza na GPW**
    Grupa Rex Concepts, operator marek Burger King i Popeyes w regionie CEE, ogłosiła zamiar przeprowadzenia pierwszej oferty publicznej (IPO). Spółka planuje pozyskać do 560 mln zł na dynamiczną ekspansję (cel to 850 lokali do 2032 r.).
    *Źródła: [Bankier.pl](https://www.bankier.pl/wiadomosc/Wielki-powrot-burgerow-na-GPW-Burger-King-i-Popeyes-zmierzaja-na-parkiet-9110410.html){rel="nofollow"}, [BiznesRadar](https://www.biznesradar.pl/wiadomosci/){rel="nofollow"}*

*   **Kadrowa „karuzela” w spółkach Skarbu Państwa**
    Odnotowano nagłe dymisje w zarządach kluczowych podmiotów: **KGHM**, **Grupy Azoty** oraz **Poczty Polskiej**. W pierwszym kwartale 2026 roku zmiany prezesów objęły już co piątą dużą spółkę z udziałem państwa.
    *Źródła: [Bankier.pl](https://www.bankier.pl/wiadomosc/Karuzela-w-spolkach-Skarbu-Panstwa-Nagle-dymisje-w-KGHM-Azotach-i-Poczcie-Polskiej-9110363.html){rel="nofollow"}, [PAP Biznes](https://pap-biznes.pl/){rel="nofollow"}*

### Otoczenie rynkowe i nastroje

*   **Rozejm USA-Iran: Ropa w dół, giełdy w górę**
    Ogłoszenie dwutygodniowego zawieszenia broni i otwarcia cieśniny Ormuz wywołało gwałtowną reakcję. Ceny ropy WTI spadły o ok. 14% (do poziomu 96 USD), a kontrakty na europejskie i amerykańskie indeksy notują solidne wzrosty przed otwarciem sesji.
    *Źródła: [Stooq](https://stooq.pl/n/?cat=1){rel="nofollow"}, [Bankier.pl](https://www.bankier.pl/wiadomosc/Rynki-swietuja-rozejm-USA-z-Iranem-Ceny-ropy-ostro-w-dol-wzrosty-na-gieldach-9110407.html){rel="nofollow"}*

*   **Podatek od nadmiarowych zysków**
    Minister Finansów Andrzej Domański zapowiedział, że projekt ustawy o nadmiarowych zyskach koncernów paliwowych będzie gotowy jeszcze w kwietniu. Informacja ta może rzutować na dzisiejsze notowania Orlenu.
    *Źródła: [Bankier.pl](https://www.bankier.pl/wiadomosc/Projekt-ustawy-o-nadmiarowych-zyskach-koncernow-paliwowych-w-kwietniu-Domanski-MF-9110421.html){rel="nofollow"}, [BiznesRadar](https://www.biznesradar.pl/wiadomosci/){rel="nofollow"}*

### Dane makro i towarowe
*   **Miedź:** Ceny w Londynie osiągnęły 3-tygodniowe maksima w związku z deeskalacją na Bliskim Wschodzie.
*   **Waluty:** Złoty umacnia się względem dolara po informacjach o rozejmie (USD/PLN w okolicach 3,64).

---
*Prasówka przygotowana na podstawie publicznych komunikatów i serwisów informacyjnych. Dane aktualne na godzinę 08:30.*
